
project_id = "mttzjxktvbsixjaqiuxq"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[functions]
[functions.process-ai-query]
verify_jwt = false

[functions.process-hierarchy]
verify_jwt = false
