project_id = "mttzjxktvbsixjaqiuxq"

[functions.calculate-demand-analytics]
verify_jwt = false

[functions.update-buffer-calculations]
verify_jwt = false

[functions.detect-breaches-and-replenish]
verify_jwt = false