name: Monthly Threshold Auto-Update

on:
  schedule:
    - cron: '0 2 1 * *' # Runs at 2 AM on the 1st of every month (KSA Time you can adjust)
  workflow_dispatch: # Allows manual trigger from GitHub

jobs:
  update-threshold:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Threshold Update Script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: |
          python analytics/threshold/threshold_update.py
