-- Insert all Burgerizzr locations with correct demographic_profile values
INSERT INTO location_master (location_id, region, restaurant_number, location_type, demographic_profile) VALUES
('LOC-001', 'Najran', 'King Fahd Rd, Najran 66231', 'Restaurant', 'URBAN'),
('LOC-002', 'Jazan', 'Corniche Rd, Jazan 82810', 'Restaurant', 'URBAN'),
('LOC-003', 'Almuruj', 'Almuruj 85533', 'Restaurant', 'SUBURBAN'),
('LOC-004', 'Abha', 'King Abdul Aziz Rd, Shamasan, Abha 62542', 'Restaurant', 'URBAN'),
('LOC-005', 'Khamis Mushait', 'Khamis Mushait 62217', 'Restaurant', 'SUBURBAN'),
('LOC-006', 'Baljurashi', 'King Abdulaziz Rd, Baljurashi 65629', 'Restaurant', 'SUBURBAN'),
('LOC-007', 'Al Bahah', 'King Fahd Rd, Alra''ib, Al Bahah 65528', 'Restaurant', 'SUBURBAN'),
('LOC-008', 'Taif', '2304 Shehar, 6934, Taif', 'Restaurant', 'URBAN'),
('LOC-009', 'Taif', 'Airport Rd, Al Faisaliyyah, Taif 26526', 'Restaurant', 'HIGHWAY'),
('LOC-010', 'Taif', 'Taif 26563', 'Restaurant', 'URBAN'),
('LOC-011', 'Makkah', 'An Naseem, Makkah 24372', 'Restaurant', 'URBAN'),
('LOC-012', 'Makkah', '2146 Al Muhandes Umar Qadi, Ar Rashidiyyah, Makkah 24268', 'Restaurant', 'URBAN'),
('LOC-013', 'Jeddah', '9075 Al Sanabel, Jeddah 22444', 'Restaurant', 'URBAN'),
('LOC-014', 'Jeddah', 'Abu Thar Al-Ghifari, An Naseem, Jeddah 23234', 'Restaurant', 'URBAN'),
('LOC-015', 'Jeddah', 'Al Andalus, Jeddah 23326', 'Restaurant', 'URBAN'),
('LOC-016', 'Jeddah', 'Al Ajawad St, Al Samer, Jeddah 23462', 'Restaurant', 'URBAN'),
('LOC-017', 'Jeddah', 'King Abdullah Rd, Jeddah 22234', 'Restaurant', 'URBAN'),
('LOC-018', 'Jeddah', '6926 King Fahad Rd, An Nuzhah, Jeddah 23532', 'Restaurant', 'URBAN'),
('LOC-019', 'Jeddah', 'Prince Majid Rd, Al Marwah, Jeddah 23541', 'Restaurant', 'URBAN'),
('LOC-020', 'Jeddah', 'Prince Sultan Rd, Al Mohammadiyyah, Jeddah 23625', 'Restaurant', 'URBAN'),
('LOC-021', 'Jeddah', 'Al Bashaer, Jeddah 23761', 'Restaurant', 'URBAN'),
('LOC-022', 'Jeddah', 'JHRA7278, Taiba, Jeddah 23832', 'Restaurant', 'URBAN'),
('LOC-023', 'Jeddah', 'Al Yaqoot, Jeddah 23826', 'Restaurant', 'URBAN'),
('LOC-024', 'Jeddah', 'Jeddah 23821', 'Restaurant', 'URBAN'),
('LOC-025', 'Madinah', '3650 8885 Abu Bakr Bin Abdullah, As Sad, Madinah 42382', 'Restaurant', 'URBAN'),
('LOC-026', 'Madinah', '7680, Madinah', 'Restaurant', 'URBAN'),
('LOC-027', 'Sufait', 'Al Sukhayrat, AlUla 43522', 'Restaurant', 'RURAL'),
('LOC-028', 'Tabuk', 'Al Imam Turki Ibn Abdullah Rd, Alulaya, Tabuk 47911', 'Restaurant', 'URBAN'),
('LOC-029', 'Al Qurayyat', 'Al Qurayyat 77453', 'Restaurant', 'SUBURBAN'),
('LOC-030', 'Hail', 'King Saud Rd, Al Matar, Hail 55421', 'Restaurant', 'HIGHWAY'),
('LOC-031', 'Hail', 'Fahd Al Ali Al Arifi, An Nuqrah, Hail 55431', 'Restaurant', 'URBAN'),
('LOC-032', 'Hafar Al Batin', '8555, Hafar Al Batin', 'Restaurant', 'SUBURBAN'),
('LOC-033', 'Unaizah', 'Al Wafaa, Unaizah 56468', 'Restaurant', 'SUBURBAN'),
('LOC-034', 'Ar Rass', 'Alhutah, Ar Rass 58839', 'Restaurant', 'SUBURBAN'),
('LOC-035', 'Al Bukayriyah', 'Al Bukayriyah 52736', 'Restaurant', 'SUBURBAN'),
('LOC-036', 'Buraydah', '4938 Internal Ring Rd, Al Basateen, Buraydah 52348', 'Restaurant', 'HIGHWAY'),
('LOC-037', 'Buraydah', 'Albossor, Buraydah 52542', 'Restaurant', 'URBAN'),
('LOC-038', 'Az Zulfi', 'King Fahd Branch Rd, Al Andalus, Az Zulfi 15942', 'Restaurant', 'HIGHWAY'),
('LOC-039', 'Al Majma''ah', 'King Abdullah Rd, Al Faiha, Al Majma''ah 15362', 'Restaurant', 'URBAN'),
('LOC-040', 'Al Duwadimi', 'King Abdulaziz Rd, Al Rayan, Al Duwadimi 17471', 'Restaurant', 'SUBURBAN'),
('LOC-041', 'Al-Kharj', 'An Nahdah, Al-Kharj 16439', 'Restaurant', 'SUBURBAN'),
('LOC-042', 'Riyadh', 'Ibn Taymeeyah Rd, Ash Shifa, Riyadh 14713', 'Restaurant', 'URBAN'),
('LOC-043', 'Riyadh', 'Western Ring Rd, Riyadh 12993', 'Restaurant', 'HIGHWAY'),
('LOC-044', 'Riyadh', 'Eastern Ring Rd, Ar Rabwah, Riyadh 12822', 'Restaurant', 'HIGHWAY'),
('LOC-045', 'Riyadh', 'Prince Turki Ibn Abdulaziz Al Awwal Rd, Riyadh 12385', 'Restaurant', 'URBAN'),
('LOC-046', 'Riyadh', 'King Abdulaziz Rd, Riyadh 13713', 'Restaurant', 'URBAN'),
('LOC-047', 'Riyadh', 'Al Malqa, Riyadh 13521', 'Restaurant', 'URBAN'),
('LOC-048', 'Riyadh', 'King Fahd Branch Rd, Al Aarid, Riyadh 13334', 'Restaurant', 'HIGHWAY'),
('LOC-049', 'Riyadh', 'Al Aarid, Riyadh 13338', 'Restaurant', 'URBAN'),
('LOC-050', 'Riyadh', 'Abi Bakr As Siddiq Rd, An Narjis, Riyadh 13333', 'Restaurant', 'URBAN'),
('LOC-051', 'Riyadh', 'King Salman Bin Abdulaziz Rd, An Narjis, Riyadh 13333', 'Restaurant', 'URBAN'),
('LOC-052', 'Riyadh', '8282 Dammam Branch Rd, Al Yarmuk, Riyadh 13251', 'Restaurant', 'HIGHWAY'),
('LOC-053', 'Riyadh', 'Ash Sharq, Riyadh 13618', 'Restaurant', 'URBAN'),
('LOC-054', 'Riyadh', 'Al Khaleej, Riyadh 13224', 'Restaurant', 'URBAN'),
('LOC-055', 'Riyadh', '2120 Khurais Rd, Al Nadwa, Riyadh 14813', 'Restaurant', 'HIGHWAY'),
('LOC-056', 'Riyadh', 'Khurais Rd, Riyadh 14241', 'Restaurant', 'HIGHWAY'),
('LOC-057', 'Riyadh', 'Dammam Branch Rd, Riyadh', 'Restaurant', 'HIGHWAY'),
('LOC-058', 'Riyadh', 'Az Zahrah, Riyadh 12985', 'Restaurant', 'URBAN'),
('LOC-059', 'Riyadh', 'Dirab Branch Rd, Alhazm, Riyadh 14964', 'Restaurant', 'HIGHWAY'),
('LOC-060', 'Riyadh', 'Al Shifa, Riyadh 13781', 'Restaurant', 'URBAN'),
('LOC-061', 'Al Ahsa (Hufuf)', '9109 Ad Dammam, Al Khars, Al Hufuf', 'Restaurant', 'URBAN'),
('LOC-062', 'Al Mubarraz', 'Al Mubarraz, Saudi Arabia', 'Restaurant', 'SUBURBAN'),
('LOC-063', 'Al Khobar', 'King Khalid Rd, Al Khuzama, Al Khobar 34719', 'Restaurant', 'URBAN'),
('LOC-064', 'Dammam', 'Omar Ibn Al Khattab St, Al Faysaliyah, Dammam 32272', 'Restaurant', 'URBAN');