// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xyglarbkjnoyqpkwvisp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5Z2xhcmJram5veXFwa3d2aXNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNjk3MzgsImV4cCI6MjA1Nzg0NTczOH0.FbDD7Q8LFd4YABzxQlBEXDsTfH9Skp8NC8xJ5-EdVbM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);